config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"

  get 'lists', to: 'lists#index', as: 'lists'
  get 'lists/new', to: 'lists#new', as: 'new_list'
  get 'lists/:id', to: 'lists#show', as: 'list'
  post 'lists', to: 'lists#create'
  get 'lists/:id/edit', to: 'lists#edit', as: 'edit_list'
  patch 'lists/:id', to: 'lists#update'
  delete 'lists/:id', to: 'lists#destroy'

  get "lists/:list_id/bookmarks/new", to: "bookmarks#new", as: :new_list_bookmark
  post "lists/:list_id/bookmarks", to: "bookmarks#create", as: :list_bookmarks
  delete "bookmarks/:id", to: "bookmarks#destroy", as: :bookmark

  # root to: "lists#index"
  # resources :lists, only: [:index, :new, :show, :create, :destroy] do
  #   resources :bookmarks, only: [:index, :new, :destroy]
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # Un film peut être dans plusieurs list mais unique dans une liste
  validates :movie, uniqueness: { scope: :list }
  validates :comment, presence: true, length: { minimum: 6 }
  # validates :comment, uniqueness: true

end

app/models/list.rb
class List < ApplicationRecord
  # destruction automatique des bookmarks dépendants si suppression list
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  # Pas de dépendance destroy entre movie et bookmarks on on ne veut pas d'automatisme
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
  # validates :poster_url, format:
  # { with: /\A(http|https):\/\/[a-zA-Z0-9\-_]+(\.[a-zA-Z0-9\-_]+)+(:\d+)?(\/[^\s]*)?\z/i,
  #   message: "is invalid" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_bookmark, only: [:destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      flash[:notice] = 'Bookmark created successfully.'
      redirect_to list_path(@list)
    else
      flash[:alert] = 'Failed to create the bookmark.'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @bookmark.destroy
      flash[:notice] = 'Bookmark deleted successfully.'
    else
      flash[:alert] = 'Failed to delete the bookmark.'
    end
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy, :edit, :update]

  def index
    @lists = List.all
  end

  def new
    @form_title = "Create a new list"
    @form_subtitle = "for your favorite movies"
    @vlabel = "Add"
    @clabel = "Cancel"
    @cpath = lists_path
    @list = List.new
  end

  def show
    @form_title = "View a list"
    @form_subtitle = "of your favorite movies"
    @clabel = "Cancel"
    @cpath = lists_path
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = 'Success'
      redirect_to lists_path
    else
      @lists = List.all
      flash.now[:alert] = "Failed".capitalize
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @form_title = "Modify your list"
    @form_subtitle = "of your favorite movies"
    @vlabel = "Modify"
    @clabel = "Cancel"
    @cpath = lists_path
  end

  def update
    if @list.update(list_params)
      flash[:notice] = 'Success'
      redirect_to list_path(@list)
    else
      flash[:alert] = 'Failed'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @list.destroy
      flash[:notice] = 'List deleted successfully.'
      redirect_to lists_path
    else
      flash[:alert] = 'Failed to delete the list.'
      redirect_to list_path(@list)
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <!-- Acces aux icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_banner.html.erb
<%# BANNER=====================================================%>
<div class="banner" style="height: 200px; background-image: url('<%= asset_path('home_bg.webp') %>');">
  <div class="container">
    <h1><%= @form_title %></h1>
    <h2><%= @form_subtitle %></h2>
  </div>
</div>

app/views/lists/_form.html.erb
<%# FORM NEW / EDIT ======c===============================================%>
<div class="container">
<%= simple_form_for(@list) do |f| %>
  <div class="form-group">
    <%= f.input :name, label: 'Name of the list' %>
  </div>

  <div class="form-group">
    <%= render 'shared/errors', object: f.object %>  <!-- Affiche les erreurs si présentes -->
  </div>

  <div class="form-group">
    <%= link_to @clabel, @cpath, class: "btn btn-secondary" %>
    <%= f.button :submit, @vlabel, class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/lists/_navbar.html.erb
<%# NAVBAR ===================================================== %>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag asset_path('logo.png') %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Lists", lists_path, class: "nav-link text-decoration-none" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "nav-link text-decoration-none" %>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<%# <%= render "banner", form_title: @form_title, form_subtitle: @form_subtitle %> %>
<%# <%= render "form", list: @list, blabel: @blabel %> %>
<%= render "banner" %>
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<%# NAVBAR ===================================================== %>
<%= render "navbar" %>

<%# BANNER ===================================================== %>

<div class="banner" style="height: 400px; background-image: url('<%= asset_path('home_bg.webp') %>');">
  <div class="container">
    <h1>Manage your own lists of favorite movies</h1>
    <h2>And share it !</h2>
  </div>
</div>

<%# MY LISTS ===================================================== %>

<div class="container">
    <div class="row align-items-center pb-4">
        <div class="col-8">
            <h1>My Lists</h1>
        </div>
        <div class="col-4 text-end">
          <%# <button class="btn btn-primary">Add a new List</button> %>
          <%= link_to 'Add a new list', new_list_path, class: 'btn btn-primary mt-4' %>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
      <% @lists.each do |list| %>
        <div id="cardlist" class="col">
            <%= link_to list_path(list), class: "text-decoration-none card-link" do %>
            <div class="card h-100">
                <div class="card-body text-center">
                    <h5 class="card-title"><%= list.name %></h5>
                </div>
            </div>
            <% end %>
        </div>
      <% end %>
    </div>
</div>

app/views/lists/new.html.erb
<%# BANNER=====================================================%>

<div class="banner" style="height: 200px; background-image: url('<%= asset_path('home_bg.webp') %>');">
  <div class="container">
    <h1>Manage your lists</h1>
    <h2>Create, Modif and Delete</h2>
  </div>
</div>

<%# FORMULAIRE=====================================================%>

<div class="container">
  <div class="row align-items-center pb-4">
    <div class="col-8">
      <div class="mb-5">

<%= form_with model: @list, url: lists_path, method: :post, local: true do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <%= form.submit "Add", class: "btn btn-primary" %>
  <% end %>

      </div>
  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>

  <% if @list.errors.any? %>
    <div class="alert alert-danger">
      <h4>Errors:</h4>
      <ul>
        <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

      <%# LISTE DES LISTS=====================================================%>

            <% @lists.each do |list| %>
            <div class="card rounded-4 px-3 mt-3 mb-3">
              <div class="row">
                <div class="col d-flex flex-column justify-content-start align-self-center">
                  <span class="fs-4 bolder"><%= list.name %></span>
                  <span class="fs-6 opacity-50"><%= list.updated_at.strftime('%d %B %Y %H:%M') %></span>
                </div>
                <div class="col d-flex justify-content-end align-items-center">
                  <span class="fs-6 opacity-50">2 movie(s)</span>
                </div>
                <div class="col d-flex justify-content-end align-items-center">
                    <i class="fa-solid fa-trash fa-1x text-black opacity-50"></i>
                </div>
              </div>
            </div>
            <% end %>

    </div>
  </div>
</div>


        <%= form_tag lists_path, method: "post" , id: "new_list_form" do %>
          <div class="modal-body">
            <div class="mb-3">
              <label for="list_name" class="form-label">Name of the list</label>
              <%= text_field_tag "list[name]" , nil, class: "form-control" , id: "list_name" %>
            </div>
            <button type="cancel" class="btn btn-secondary">Cancel</button>
            <button type="submit" class="btn btn-primary">Add</button>
          </div>
        <% end %>

app/views/lists/show.html.erb
<%# <%= render "banner", form_title: @form_title, form_subtitle: @form_subtitle %> %>
<%= render "navbar" %>
<%= render "banner" %>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this item?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <%= button_to "Delete", list_path(@list), method: :delete, class: "btn btn-danger", form: { id: "deleteForm" } %>
      </div>
    </div>
  </div>
</div>


<%# SHOW ======c===============================================%>
<div class="container">
  <div class="form-group">
    <label for="list_name">Name of the list</label>
    <input type="text" class="form-control" value="<%= @list.name %>" disabled>
  </div>
</div>

<div class="container form-group mt-3 mb-5 pt-0">
  <%= link_to @clabel, @cpath, class: "btn btn-secondary" %>
  <%= link_to "Edit", edit_list_path(@list), class: "btn btn-primary" %>
  <%# <%= link_to "Delete", list_path(@list), data: {turbo_method: "delete", turbo_confirm: "are you sure ?"}, class: "btn btn-danger" %>
  <%= link_to "Delete", "#", class: "btn btn-danger text-white", data: { bs_toggle: "modal", bs_target: "#deleteModal" } %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name.downcase %> from being saved:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>